# Name: Gayatri Bhosale
### PRN: 25070123033
## Experiment 8: Tools in EDA Numpy Pandas


In [ ]:
# Why NumPy
#faster than list
#used for numerical computations
#Base of pandas

In [2]:
import numpy as np
a = np.array([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [4]:
#Dimension of Array
print(a.ndim)
print(b.ndim)


1
2


In [8]:
print(a.shape)
print(b.shape)


(4,)
(2, 3)


In [22]:
print(a.dtype)
print(b.dtype)

int64
int64


In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
c=a*2
d=a+5
print(c)
print(d)

[20 40 60 80]
[15 25 35 45]


In [36]:
a+5

array([15, 25, 35, 45])

In [46]:
np.mean(a)
np.mean(b)

np.float64(3.5)

In [50]:
print(np.median(a))
print(np.median(b))

25.0
3.5


In [47]:
print(np.max(a))
print(np.max(b))

40
6


In [51]:
np.min(a)
np.min(b)

np.int64(1)

In [55]:
np.sum(a)
np.sum(b)

np.int64(21)